package:
  name: stitch-workspace
  version: 0.0.4

build:
  number: 0
  noarch: generic
  script:
    - mkdir -p $PREFIX/src/tools
    - cp -r $RECIPE_DIR/stitch $PREFIX/src/tools/
    - cp $RECIPE_DIR/WORKSPACE $PREFIX/src/
    - cp $RECIPE_DIR/stitch.bazelrc $PREFIX/src/.bazelrc

test:
  exists:
    files:
      - src/WORKSPACE
      - src/.bazelrc
      - src/tools/stitch/repositories.bzl
      - src/BUILD

# Bazel should really be requiring coreutils
requirements:
  run:
    - bazel
    - coreutils

about:
  home: https://github.com/eyepatchParrot/conda_stitch
  summary: 'Stitch bazel workspace from conda packages'
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - eyepatchParrot
