package:
  name: stitch-workspace
  version: 0.0.2

build:
  number: 1
  noarch: generic
  script:
    - mkdir -p $PREFIX/src
    - cp -r $RECIPE_DIR/tools $PREFIX/src/
    - cp $RECIPE_DIR/WORKSPACE $PREFIX/src/
    - cp $RECIPE_DIR/stitch.bazelrc $PREFIX/src/.bazelrc

test:
  exists:
    files:
      - src/WORKSPACE
      - src/.bazelrc
      - src/tools/stitch/repositories.bzl

about:
  home: https://github.com/eyepatchParrot/conda_stitch
  summary: 'Stitch bazel workspace from conda packages'
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - eyepatchParrot
