package:
  name: 'stitch-doctest'
  version: '2.4.8'

build:
  number: 2
  script:
    - mkdir -p $PREFIX/src/src
    - cp -r $RECIPE_DIR/doctest $PREFIX/src/src

requirements:
    run:
        - doctest

test:
  exists:
    files:
      - src/src/doctest/BUILD
      - src/src/doctest/doctest.h
      - src/src/doctest/doctest/doctest.h

extra:
  recipe-maintainers:
    - eyepatchParrot
