# Order relies on first entry not being in a sub directory
filegroup(name="unicode.org-ucd", srcs = [
":CaseFolding.txt",
":PropList.txt",
":DerivedCoreProperties.txt",
":extracted/DerivedGeneralCategory.txt",
], visibility=["//visibility:public"])
