package:
  name: stitch-buildbuddy
  version: 0.0.1

build:
  number: 0
  script:
    - mkdir -p $PREFIX/src/tools
    - cp -r $RECIPE_DIR/buildbuddy $PREFIX/src/tools

test:
  exists:
    files:
      - src/tools/buildbuddy/buildbuddy.bazelrc

requirements:
  run:
    - stitch-workspace
    - bazel

about:
  home: 'https://github.com/eyepatchParrot/conda_stitch'
  summary: 'C++ toolchain'
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - eyepatchParrot
