context:
  name: stitch-rust
  version: 0.4.0
  github: https://github.com/bazelbuild/rules_rust

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

build:
  number: 7
  noarch: generic

requirements:
  run:
    - stitch-workspace
    - stitch-bazel-skylib

source:
  - url: '{{ github }}/archive/refs/tags/{{ version }}.tar.gz'
    sha256: 067f73fa55c4a7518609c56a7698592ba488abbc2f78dc896ef477062300a2e7
    folder: rules_rust
  - url: 'https://crates.io/api/v1/crates/tinyjson/2.3.0/download'
    sha256: 1a8304da9f9370f6a6f9020b7903b044aa9ce3470f300a1fba5bc77c78145a16
    fn: tinyjson.tgz
    folder: rules_rust_tinyjson

about:
  home: '{{ github }}'
  summary: 'Rust rules for Bazel'
  license: Apache
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - eyepatchParrot
