package:
  name: 'stitch-src-kakoune'
  version: '2022.06.12'

source:
  path: ../../kakoune
  folder: kakoune

build:
  number: 0
  script:
    - mkdir $PREFIX/src
    - cp -r kakoune $PREFIX/src
    - cp $RECIPE_DIR/BUILD $PREFIX/src/kakoune/BUILD
    - cp $RECIPE_DIR/doc.BUILD $PREFIX/src/kakoune/doc/BUILD
    - cp $RECIPE_DIR/src.BUILD $PREFIX/src/kakoune/src/BUILD

about:
  home: 'https://github.com/mawww/kakoune'
  summary: 'Modal editor — Faster as in fewer keystrokes — Multiple selections — Orthogonal design'
  license: OTHER
  license_file: UNLICENSE

extra:
  recipe-maintainers:
    - eyepatchParrot
