context:
  name: noactivate-env
  version: 0.0.1

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

build:
  number: 13
  noarch: generic
  script:
    - set -x
    - cp -r $RECIPE_DIR/share $PREFIX
    - mkdir -p "$PREFIX/etc/conda/activate.d"
    - cp "$RECIPE_DIR/activate.sh" "${PREFIX}/etc/conda/activate.d/$PKG_NAME_activate.sh"

about:
  home: https://github.com/eyepatchParrot/conda_stitch
  summary: 'Conda without the activation'
  license: BSD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - eyepatchParrot
