# gxx would probably be a better name
package:
  name: 'stitch-tools-cpp'
  version: 0.0.1

build:
  number: 1
  script:
    - mkdir -p $PREFIX/src/tools ; cp -r $RECIPE_DIR/cpp $PREFIX/src/tools

test:
  files:
    - test_cpp/test_cpp.cc
    - test_cpp/BUILD
  commands:
    - cp -r test_cpp $PREFIX/src/tools ; cd $PREFIX/src
    - bazel test //tools/test_cpp ; bazel clean
    - bazel test --config=buildbuddy //tools/test_cpp ; bazel clean
    - bazel clean --expunge
    - bazel shutdown
  requires:
    - stitch-buildbuddy
  exists:
    files:
      - src/tools/cpp/toolchain/bin/x86_64-conda-linux-gnu-cpp
      - src/tools/cpp/toolchain/BUILD
      - src/tools/cpp/toolchain/libexec/gcc
      - src/tools/cpp/toolchain/lib/gcc
      - src/tools/cpp/toolchain/lib/libgcc_s.so.1

requirements:
  run:
    - stitch-workspace
    - bazel
    - gxx

about:
  home: 'https://github.com/eyepatchParrot/conda_stitch'
  summary: 'C++ toolchain'
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - eyepatchParrot
