context:
  source_url: https://www.unicode.org/Public/
  version: 14.0.0
  parent: "$PREFIX/src/src"

package:
  name: stitch-unicode.org-ucd
  version: '{{ version }}'

build:
  number: 0
  script:
    - mkdir -p "{{ parent }}"
    - cp -r $RECIPE_DIR/unicode.org-ucd "{{ parent }}"
    - find "{{ parent }}/unicode.org-ucd" -type l -exec rm {} +
    - cp DerivedGeneralCategory.txt "{{ parent }}/unicode.org-ucd/extracted"
    - cp *.txt "{{ parent }}/unicode.org-ucd"

requirements:
  run:
    - stitch-workspace

test:
  exists:
    files:
      - src/unicode.org/ucd/extracted/DerivedGeneralCategory.txt
      - src/unicode.org/ucd/CaseFolding.txt
      - src/unicode.org/ucd/BUILD

source:
  - url: '{{ source_url }}/{{ version }}/ucd/extracted/DerivedGeneralCategory.txt'
    sha256: cde679c8461976ed40d7edf61ae98cbb947540831f06f5bc7da7decbf91a1420
  - url: '{{ source_url }}/{{ version }}/ucd/CaseFolding.txt'
    sha256: a566cd48687b2cd897e02501118b2413c14ae86d318f9abbbba97feb84189f0f
  - url: '{{ source_url }}/{{ version }}/ucd/PropList.txt'
    sha256: 6bddfdb850417a5bee6deff19290fd1b138589909afb50f5a049f343bf2c6722
  - url: '{{ source_url }}/{{ version }}/ucd/DerivedCoreProperties.txt'
    sha256: e3eddd7d469cd1b0feed7528defad1a1cc7c6a9ceb0ae4446a6d10921ed2e7bc

extra:
  recipe-maintainers:
    - eyepatchParrot
