context:
  name: bazel-skylib
  version: 1.2.0
  github: https://github.com/bazelbuild/bazel-skylib

package:
  name: 'stitch-{{ name|lower }}'
  version: '{{ version }}'

build:
  number: 2
  noarch: generic

requirements:
  run:
    - stitch-workspace

source:
  url: '{{ github }}/releases/download/{{ version }}/{{ name }}-{{ version }}.tar.gz'
  sha256: af87959afe497dc8dfd4c6cb66e1279cb98ccc84284619ebfec27d9c09a903de

about:
  home: '{{ github }}'
  summary: 'Common useful functions and rules for Bazel'
  license: Apache
  license_file: LICENSE

extra:
  recipe-maintainers:
    - eyepatchParrot
