package:
  name: 'stitch-kakoune'
  version: '2022.06.12'

build:
  number: 0
  script:
    - cd $BUILD_PREFIX/src
    - bazel build //kakoune
    - cd kakoune/src
    - install -d $PREFIX/bin $PREFIX/share/kak/rc $PREFIX/share/kak/colors $PREFIX/share/kak/doc $PREFIX/share/doc/kak $PREFIX/share/man/man1
    - install -m 0755 ../../bazel-bin/kakoune/src/kakoune $PREFIX/bin/kak
    - install -m 0644 ../share/kak/kakrc $PREFIX/share/kak
    - install -m 0644 ../doc/pages/*.asciidoc $PREFIX/share/kak/doc
    - cp -r ../rc/* $PREFIX/share/kak/rc
    - find $PREFIX/share/kak/rc -type f -exec chmod 0644 {} +
    - "[ -e $PREFIX/share/kak/autoload ] || ln -s rc $PREFIX/share/kak/autoload"
    - install -m 0644 ../colors/* $PREFIX/share/kak/colors
    - install -m 0644 ../README.asciidoc $PREFIX/share/doc/kak
    - install -m 0644 ../../bazel-bin/kakoune/doc/kak.1.gz $PREFIX/share/man/man1

requirements:
  build:
    - bazel
    - stitch-workspace
    - stitch-src-kakoune

about:
  home: 'https://github.com/mawww/kakoune'
  summary: 'Modal editor — Faster as in fewer keystrokes — Multiple selections — Orthogonal design'
  license: OTHER
  license_file: UNLICENSE

extra:
  recipe-maintainers:
    - eyepatchParrot
